# Generated by Django 3.2.15 on 2022-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app04_movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='seasons',
            field=models.SmallIntegerField(default=0, verbose_name='Сезоны'),
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.SmallIntegerField(default=0, verbose_name='Серии'),
        ),
    ]
