# Generated by Django 3.2.15 on 2022-09-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04_movies', '0002_auto_20220914_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='fees_in_usa',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fess_in_world',
        ),
    ]
