# Generated by Django 3.2.15 on 2022-09-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04_movies', '0003_auto_20220914_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
    ]
