# Generated by Django 3.2.15 on 2022-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app04_movies', '0004_remove_movie_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default=2, max_length=150, verbose_name='Трейлер'),
            preserve_default=False,
        ),
    ]
