# Generated by Django 3.2.15 on 2022-11-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04_movies', '0007_auto_20221006_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshots',
            name='description',
        ),
    ]
